# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [20]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [21]:
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep3179274605568
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [22]:
a = np.random.random((2, 3, 5))


### 4. Print a.


In [23]:
print(a)

[[[0.52285638 0.93381046 0.11953317 0.57692528 0.78685074]
  [0.91912712 0.95311366 0.57705117 0.54194593 0.97176879]
  [0.94608057 0.0990428  0.50131184 0.0721049  0.69788297]]

 [[0.65402987 0.40069803 0.84266674 0.13155469 0.44307265]
  [0.45545482 0.28013976 0.85106927 0.28840367 0.57792836]
  [0.01016656 0.14115213 0.64811936 0.86602371 0.05558078]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [24]:
b = np.ones((5, 2, 3))


### 6. Print b.


In [25]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [26]:
if a.size == b.size:
    print("They have the same size!")
else:
    print("They do not.")

They have the same size!



### 8. Are you able to add a and b? Why or why not?


In [27]:
try:
    result = a + b
except ValueError as e:
    print(f"Error: {e}")

#The shapes don't match.

Error: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [28]:
c = b.transpose(1, 2, 0)


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [29]:
d = a + c


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [30]:
print("Array a:\n", a)
print("Array d:\n", d)
#d is the element-wise sum of a and c.

Array a:
 [[[0.52285638 0.93381046 0.11953317 0.57692528 0.78685074]
  [0.91912712 0.95311366 0.57705117 0.54194593 0.97176879]
  [0.94608057 0.0990428  0.50131184 0.0721049  0.69788297]]

 [[0.65402987 0.40069803 0.84266674 0.13155469 0.44307265]
  [0.45545482 0.28013976 0.85106927 0.28840367 0.57792836]
  [0.01016656 0.14115213 0.64811936 0.86602371 0.05558078]]]
Array d:
 [[[1.52285638 1.93381046 1.11953317 1.57692528 1.78685074]
  [1.91912712 1.95311366 1.57705117 1.54194593 1.97176879]
  [1.94608057 1.0990428  1.50131184 1.0721049  1.69788297]]

 [[1.65402987 1.40069803 1.84266674 1.13155469 1.44307265]
  [1.45545482 1.28013976 1.85106927 1.28840367 1.57792836]
  [1.01016656 1.14115213 1.64811936 1.86602371 1.05558078]]]



### 12. Multiply a and c. Assign the result to e.


In [31]:
e = a * c



### 13. Does e equal to a? Why or why not?


In [32]:
print(np.array_equal(a, e))
#Because the multiplication will scale the values differently.

True




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [33]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)


### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [34]:
f = np.empty(d.shape)




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [35]:
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [36]:
print("Array d:\n", d)
print("Array f:\n", f)

Array d:
 [[[1.52285638 1.93381046 1.11953317 1.57692528 1.78685074]
  [1.91912712 1.95311366 1.57705117 1.54194593 1.97176879]
  [1.94608057 1.0990428  1.50131184 1.0721049  1.69788297]]

 [[1.65402987 1.40069803 1.84266674 1.13155469 1.44307265]
  [1.45545482 1.28013976 1.85106927 1.28840367 1.57792836]
  [1.01016656 1.14115213 1.64811936 1.86602371 1.05558078]]]
Array f:
 [[[ 25.  75.  25.  75.  75.]
  [ 75.  75.  75.  75. 100.]
  [ 75.  25.  25.  25.  75.]]

 [[ 75.  25.  75.  25.  25.]
  [ 25.  25.  75.  25.  75.]
  [  0.  25.  75.  75.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [37]:
f_strings = np.empty(d.shape, dtype="<U1")

f_strings[(d > d_min) & (d < d_mean)] = 'B'
f_strings[(d > d_mean) & (d < d_max)] = 'D'
f_strings[d == d_mean] = 'C'
f_strings[d == d_min] = 'A'
f_strings[d == d_max] = 'E'

print("Array with string labels:\n", f_strings)

Array with string labels:
 [[['B' 'D' 'B' 'D' 'D']
  ['D' 'D' 'D' 'D' 'E']
  ['D' 'B' 'B' 'B' 'D']]

 [['D' 'B' 'D' 'B' 'B']
  ['B' 'B' 'D' 'B' 'D']
  ['A' 'B' 'D' 'D' 'B']]]
